# Generated by Django 5.2.1 on 2025-06-18 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('sale_state', models.CharField(choices=[('P', 'PENDING PAY'), ('S', 'SENT'), ('C', 'CANCELED'), ('R', 'RECEIVED')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('ADMIN', 'ADMINISTRADOR'), ('USER', 'CLIENTE')], default='USER', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=255)),
                ('trade_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Detail_Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.products')),
                ('sale_oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.sales')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.products')),
            ],
        ),
        migrations.AddField(
            model_name='sales',
            name='user_oid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.users'),
        ),
        migrations.CreateModel(
            name='Cart_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateField(auto_created=True)),
                ('quantity', models.IntegerField()),
                ('Product_oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.products')),
                ('user_oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.users')),
            ],
        ),
    ]
