# Generated by Django 5.2.1 on 2025-06-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='added_at',
            field=models.DateField(auto_now=True),
        ),
    ]
