# Generated by Django 5.2.1 on 2025-06-18 21:23

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_cart_items_added_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CO')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='products',
            old_name='categoria',
            new_name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default='No hay descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.TextField(default='No tiene imagen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='iva_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='sale_mode',
            field=models.CharField(choices=[('O', 'ONLINE'), ('P', 'PRESENCIAL'), ('D', 'DOMICILIO')], default='P', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
